version: '3'

services:
  database:
    image: "postgres:latest"
    container_name: map_tool_postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer_password
      - POSTGRES_DB=map_tool_database

    volumes:
      - ./docker/database-data:/var/lib/postgresql/data/

volumes:
  database-data: